find_path(BENCHMARKR_DEV_INCLUDE_DIR NAMES benchmarkr.h)

find_library(BENCHMARKR_DEV_LIBRARY NAMES benchmarkr-dev)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(BENCHMARKR_DEV REQUIRED_VARS BENCHMARKR_DEV_LIBRARY BENCHMARKR_DEV_INCLUDE_DIR)

if(BENCHMARKR_DEV_FOUND)
    set(BENCHMARKR_DEV_LIBRARIES ${BENCHMARKR_DEV_LIBRARY})
    set(BENCHMARKR_DEV_INCLUDE_DIRS ${BENCHMARKR_DEV_INCLUDE_DIR})
endif()
